package com.sems.dao;

import com.sems.model.*;
import java.util.List;
import java.sql.Date; // Added for DOB handling

public class UserDAOTest {

    public static void main(String[] args) {
        // 1. Initialize all DAOs
        UserDAO userDAO = new UserDAO();
        StudentDAO studentDAO = new StudentDAO();
        CourseDAO courseDAO = new CourseDAO();
        EnrollmentDAO enrollmentDAO = new EnrollmentDAO();

        System.out.println("--- SEMS FULL SYSTEM INTEGRATION TEST ---");

        // STEP 1: Create a User (The Login)
        String uniqueUsername = "student_" + System.currentTimeMillis(); 
        User user = new User(uniqueUsername, "pass123", "student");
        user.setIsActive(true);
        int userId = userDAO.createUser(user);

        if (userId != -1) {
            System.out.println("[OK] User created. ID: " + userId);

            // STEP 2: Create a Student Profile (The Person)
            Student student = new Student();
            student.setUserId(userId);
            student.setFirstName("Maisarah");
            student.setLastName("Abjalil");
            student.setEmail("mai_" + System.currentTimeMillis() + "@example.com"); // Unique email
            
            // --- NEW FIELDS ADDED HERE ---
            student.setPhone("012-3456789");
            student.setAddress("123 Java Lane, SQL City");
            student.setGpa(3.85);
            
            // This fixes the 'dob' doesn't have a default value error
            student.setDob(Date.valueOf("2000-01-01")); 
            
            boolean studentCreated = studentDAO.createStudent(student);
            
            if (studentCreated) {
                System.out.println("[OK] Student profile linked to User.");
                
                // Fetch the student_id generated by MySQL
                Student registeredStudent = studentDAO.getStudentByUserId(userId);
                int studentId = registeredStudent.getStudentId();

                // STEP 3: Create a Course
                Course course = new Course();
                course.setCourseCode("CS102-" + System.currentTimeMillis() % 1000); // Unique code
                course.setCourseName("Data Structures");
                course.setCredits(4);
                course.setCapacity(30);
                
                courseDAO.createCourse(course);
                System.out.println("[OK] Course added to catalog.");
                
                // Get the latest course_id
                List<Course> allCourses = courseDAO.getAllCourses();
                int courseId = allCourses.get(allCourses.size() - 1).getCourseId();

                // STEP 4: Enroll Student in Course
                System.out.println("Attempting enrollment...");
                boolean enrolled = enrollmentDAO.enrollStudent(studentId, courseId);
                
                if (enrolled) {
                    // STEP 5: Update Course Count
                    courseDAO.incrementEnrolledCount(courseId);
                    
                    System.out.println("------------------------------------------");
                    System.out.println("[SUCCESS] Full System Flow Complete!");
                    System.out.println("Username: " + uniqueUsername);
                    System.out.println("Student ID: " + studentId + " | Course ID: " + courseId);
                    System.out.println("------------------------------------------");
                }
            } else {
                System.out.println("[ERROR] Failed to create Student Profile.");
            }
        } else {
            System.out.println("[ERROR] System test failed at Step 1 (User creation).");
        }
    }
}